package com.ruse.webhooks.discord;

import java.awt.Color;
import java.net.URI;

import ca.momoperes.canarywebhooks.DiscordMessage;
import ca.momoperes.canarywebhooks.WebhookClient;
import ca.momoperes.canarywebhooks.WebhookClientBuilder;
import ca.momoperes.canarywebhooks.embed.DiscordEmbed;
import com.ruse.util.Misc;
import org.json.JSONObject;


public class DiscordMessager extends JSONObject { 
	
	public static boolean active = false;
	
	private static String testhook = webhook("TEST");
	private static String announcementhook = webhook("ANNOUNCEMENT");
	private static String staffhook = webhook("STAFF");
	private static String ingamehook = webhook("INGAME");
	private static String debughook = webhook("DEBUG");
	private static String yellhook = webhook("YELL");
	private static String pmhook = webhook("PM");
	private static String chathook = webhook("CHAT");
	private static String clanhook = webhook("CLAN");

	private static String webhook(String channel) {
		String value = environment("PSYCHO_DISCORD_WEBHOOK_" + channel);
		if (value == null || value.trim().isEmpty()) {
			value = environment("KANDARIN_DISCORD_WEBHOOK_" + channel);
		}
		return value;
	}

	private static String environment(String environmentVariable) {
		String value = System.getenv(environmentVariable);
		return value == null || value.trim().isEmpty() ? null : value.trim();
	}

	private static boolean disabled(String webhook) {
		return Misc.checkForOwner() || !active || webhook == null || webhook.isEmpty();
	}
	
	public static void test(String msg) {
		try {
			
			String webhook = testhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("PsychoticRSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.YELLOW) // The color of the embed. You can leave this at null for no color
				    .withDescription("This message was generated by the server.") // The description of the embed object
				    .build(); // Build the embed element
			
			if (msg == null || msg == "") {
				msg = new String("```hi this is a server test``` @everyone @crimson @crimson#2406 test \"quotes\" \nnewline :fire: :100: :ironman:");
			}
			
			DiscordMessage message = new DiscordMessage.Builder(Misc.stripIngameFormat(msg)) // The content of the message
				    .withEmbed(embed) // Add our embed object
				    .withUsername("Psycho Bot") // Override the username of the bot
				    .build(); // Build the message
			
			client.sendPayload(message);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendAnnouncement(String msg) {
		try {
			
			String webhook = announcementhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    .withTitle("Psycho - RSPS") // The title of the embed element
				    .withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.GREEN) // The color of the embed. You can leave this at null for no color
				    .withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			DiscordMessage message = new DiscordMessage.Builder(Misc.stripIngameFormat(msg)) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Announcement Bot") // Override the username of the bot
				    .build(); // Build the message
			
			client.sendPayload(message);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendStaffMessage(String msg) {
		try {
			
			String webhook = staffhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.ORANGE) // The color of the embed. You can leave this at null for no color
				    .withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			DiscordMessage message = new DiscordMessage.Builder(Misc.stripIngameFormat(msg)) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Staff Bot") // Override the username of the bot
				    .build(); // Build the message
			
			client.sendPayload(message);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendChatMessage(String msg) {
		try {
			
			String webhook = chathook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.YELLOW) // The color of the embed. You can leave this at null for no color
				    //.withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			String msgToSend = Misc.stripIngameFormat(msg);
			
			DiscordMessage message = new DiscordMessage.Builder(msgToSend) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Chat Bot") // Override the username of the bot
				    .build(); // Build the message
			
			if (msgToSend.equalsIgnoreCase(":information_source:!")) {
				sendDebugMessage("Bad message from sendChatMessage, \n"+msgToSend);
			} else {
				client.sendPayload(message);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendClanMessage(String msg) {
		try {
			
			String webhook = clanhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.GREEN) // The color of the embed. You can leave this at null for no color
				    //.withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			String msgToSend = Misc.stripIngameFormat(msg);
			
			DiscordMessage message = new DiscordMessage.Builder(msgToSend) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Clan Bot") // Override the username of the bot
				    .build(); // Build the message
			
			if (msgToSend.equalsIgnoreCase(":information_source:!")) {
				sendDebugMessage("Bad message from sendClanMessage, \n"+msgToSend);
			} else {
				client.sendPayload(message);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendPrivateMessage(String msg) {
		try {
			
			String webhook = pmhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.MAGENTA) // The color of the embed. You can leave this at null for no color
				    //.withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			String msgToSend = Misc.stripIngameFormat(msg);
			
			DiscordMessage message = new DiscordMessage.Builder(msgToSend) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Privacy Bot") // Override the username of the bot
				    .build(); // Build the message
			
			if (msgToSend.equalsIgnoreCase(":information_source:!")) {
				sendDebugMessage("Bad message from sendPrivateMessage, \n"+msgToSend);
			} else {
				client.sendPayload(message);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendInGameMessage(String msg) {
		try {
			
			String webhook = ingamehook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.BLUE) // The color of the embed. You can leave this at null for no color
				    .withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			String msgToSend = Misc.stripIngameFormat(msg);
			
			DiscordMessage message = new DiscordMessage.Builder(msgToSend) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("In-Game Bot") // Override the username of the bot
				    .build(); // Build the message
			
			if (msgToSend.equalsIgnoreCase(":information_source:!")) {
				sendDebugMessage("Bad message from sendInGameMessage, \n"+msgToSend);
			} else {
				client.sendPayload(message);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendDebugMessage(String msg) {
		try {
			
			String webhook = debughook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    .withTitle("Psycho - RSPS") // The title of the embed element
				    .withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.MAGENTA) // The color of the embed. You can leave this at null for no color
				    .withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			//DiscordMessage message = new DiscordMessage.Builder(msg) 
			DiscordMessage message = new DiscordMessage.Builder(Misc.stripIngameFormat(msg)) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Debug Bot") // Override the username of the bot
				    .build(); // Build the message
			
			client.sendPayload(message);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void sendYellMessage(String msg) {
		try {
			
			String webhook = yellhook;
			if (disabled(webhook)) {
				return;
			}
			
			WebhookClient client = new WebhookClientBuilder()
				    .withURI(new URI(webhook))
				    .build(); // Create the webhook client
			
			DiscordEmbed embed = new DiscordEmbed.Builder()
				    //.withTitle("Psychotic - RSPS") // The title of the embed element
				    //.withURL("https://playpsycho.local/") // The URL of the embed element
				    .withColor(Color.WHITE) // The color of the embed. You can leave this at null for no color
				    .withDescription("Remember, you can mute any specific channel by clicking the bell in the top right of Discord.") // The description of the embed object
				    .build(); // Build the embed element
			
			String msgToSend = Misc.stripIngameFormat(msg);
			
			DiscordMessage message = new DiscordMessage.Builder(msgToSend) // The content of the message
				    //.withEmbed(embed) // Add our embed object
				    .withUsername("Yell Bot") // Override the username of the bot
				    .build(); // Build the message
			
			if (msgToSend.equalsIgnoreCase(":information_source:!")) {
				sendDebugMessage("Bad message from sendYellMessage, \n"+msgToSend);
			} else {
				client.sendPayload(message);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	
	/*System.out.println("test");
	URL url = new URL(System.getenv("PSYCHO_DISCORD_WEBHOOK_TEST"));
	HttpURLConnection conn = (HttpURLConnection) url.openConnection();
	conn.setDoOutput(true);
	conn.setRequestMethod("POST");
	conn.setRequestProperty("Content-Type", "application/json; charset=UTF-8");
	conn.setRequestProperty("Accept", "application/json; charset=UTF-8");
	
	JSONObject discord = new JSONObject();
	
	//ARGS: username, content, avatar_url, tts
	discord.put("username", "test");
	discord.put("content", "@everyone hallo it is me a fRIENDD!@@#!@#!@#!@#!@#!@#!@#!@#!@#");
	
	//discord.put("avatar_url", "http://i.imgur.com/4Da0jRZ.png");
	//discord.put("tts", false);
	
	OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());
	discord.write(wr);
	wr.flush();
	
	StringBuilder sb = new StringBuilder();  
	int HttpResult = conn.getResponseCode(); 
	if (HttpResult == HttpURLConnection.HTTP_OK) {
		System.out.println("HTTP = OK");
	    BufferedReader br = new BufferedReader(
	            new InputStreamReader(conn.getInputStream(), "utf-8"));
	    String line = null;  
	    while ((line = br.readLine()) != null) {  
	        sb.append(line + "\n");  
	    }
	    br.close();
	    System.out.println("" + sb.toString());  
	} else {
		System.out.println("HTTP = NOT OK");
	    System.out.println(conn.getResponseMessage());  
	}  */

}
