plugins {
    id 'java'
    id 'war' // Gives access to providedCompile()
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_12
    targetCompatibility = JavaVersion.VERSION_12
}

mainClassName = 'com.ruse.GameServer'

task exportUnityMirror(type: JavaExec) {
    group = 'psycho'
    description = 'Exports authoritative Java server definitions for the Unity mirror client.'
    classpath = sourceSets.main.runtimeClasspath
    main = 'com.ruse.tools.UnityMirrorExportTool'
    workingDir = project.projectDir
    args = [project.findProperty('unityMirrorOut') ?: '../psycho_unity_client/Assets/StreamingAssets/PsychoMirror']
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
    }
    test {
        java {
            srcDir 'src/test/java'
        }
    }
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'

    implementation fileTree(dir: 'lib', include: ['*.jar'])
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.30'
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.30'
    implementation group: 'org.javacord', name: 'javacord', version: '3.0.4'
    implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.10.1'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.10.1'
    implementation group: 'org.jsoup', name: 'jsoup', version: '1.11.3'
}
